### ISSUE TITLE
删除并重新添加图片时会产生的疑似BUG

### ISSUE THREAD

**Issue by NamelessAstral** [LuiScreaMed/karasubonk#1]
在投掷物图片选项卡内删除并重新添加相同名称的图片时，会在原本的文件名最后添加一个序号，如“小花花2,png”。
在karasubonk_bilibili-win32\resources\app\throws文件夹中，会存留之前已删除的图片。
并且，若尝试手动删除文件夹内的图片，已删除的图片会在程序下次启动时再次出现。

**Comment by LuiScreaMed** [comment]
这个是原作者的写法，b站版本下个版本会在删除投掷物后同时删除文件。另外还会添加替换功能。
对于手动删除后依然存在，是因为存档位于 `%APPDATA%/karasubonk_bilibili`，开启app后会将存档的投掷物图片等等资源复制覆盖到app的resource目录（为方便bonker.html取用资源）。
